apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: vote
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-redis-secret
                key: host
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-redis-secret
                key: password
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-redis-secret
                key: port
          - name: REDIS_URI
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-redis-secret
                key: uri
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
